name: Database connector request
about: Suggest a database you would like to connect to Evidence
title: '[Connector]: '
labels: connectors
assignees: ''
body:
  - type: textarea
    id: use-csae
    attributes:
      label: What do you use this database for?
      description: Is this your primary analytics data warehouse? Do you use it for a specific type or a specific source of data?
      placeholder: Use case
    validations:
      required: true
  - type: textarea
    id: clients
    attributes:
      label: Are there any popular and well-maintained clients for this database?
      description: E.g., npm packages we should consider using
      placeholder: Existing clients
    validations:
      required: true
