name: E2E Tests

on:
  # TODO remove once we know this action is working correctly
  push:
    branches: [test/2255-hmr-tests]
    
  pull_request:
    branches: [main, next]

jobs:
  find-e2e-test-projects:
    name: Find E2E Test Projects
    runs-on: ubuntu-latest
    outputs:
      e2e-test-projects: ${{ steps.e2e-test-projects.outputs.e2e-test-projects }}
    steps:
      - uses: actions/checkout@v4
      
      - id: e2e-test-projects
        run: echo "e2e-test-projects=$(find e2e -maxdepth 1 -type d -printf "%f\n" | jq --raw-input --slurp --compact-output 'split("\n")[1:-1]')" >> ${GITHUB_OUTPUT}

  run-tests:
    needs:
      - find-e2e-test-projects
    strategy:
      matrix:
        project: ${{ fromJson(needs.find-e2e-test-projects.outputs.e2e-test-projects) }}
    name: ${{ matrix.project }} tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Action Setup (pnpm)
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # TODO: I think we could do installation in a previous job and share files between the jobs using upload/download artifact to speed up this action
      # https://stackoverflow.com/a/75021352/9080819
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright and browsers
        run: pnpm playwright install --with-deps

      - name: Go to project directory
        run: cd e2e/${{ matrix.project }}

      - name: Run dev mode tests
        run: pnpm run test:dev

      - name: Build
        run: pnpm run build

      - name: Run preview mode tests
        run: pnpm run test:preview

      - name: Upload Playwright reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project}}/playwright-reports
          path: ./playwright-reports
